services:
  db:
    image: postgres:16-alpine
    ports:
      - 54320:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/